// <auto-generated />
using System;
using BeautySalon.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeautySalon.DAL.Migrations
{
    [DbContext(typeof(BeautySalonDBContext))]
    [Migration("20260523195156_AddSchedulePhotoRatingSeedData")]
    partial class AddSchedulePhotoRatingSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BeautySalon.DAL.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hair Care",
                            PhotoUrl = "category_hair.png"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nails",
                            PhotoUrl = "category_nails.png"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Makeup",
                            PhotoUrl = "category_makeup.png"
                        });
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Watson",
                            PhoneNumber = "+380001111111",
                            PhotoUrl = "master_hair1.png",
                            Position = "Top Hair Stylist",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Smith",
                            PhoneNumber = "+380002222222",
                            PhotoUrl = "master_hair2.png",
                            Position = "Hair Stylist",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            PhoneNumber = "+380003333333",
                            PhotoUrl = "master_hair3.png",
                            Position = "Expert Colorist",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Brown",
                            PhoneNumber = "+380004444444",
                            PhotoUrl = "master_hair4.png",
                            Position = "Junior Hair Stylist",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Jessica",
                            IsActive = true,
                            LastName = "Davis",
                            PhoneNumber = "+380005555555",
                            PhotoUrl = "master_nails1.png",
                            Position = "Top Nail Master",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Miller",
                            PhoneNumber = "+380006666666",
                            PhotoUrl = "master_nails2.png",
                            Position = "Senior Nail Technician",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Anna",
                            IsActive = true,
                            LastName = "Wilson",
                            PhoneNumber = "+380007777777",
                            PhotoUrl = "master_nails3.png",
                            Position = "Nail Technician",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Taylor",
                            PhoneNumber = "+380008888888",
                            PhotoUrl = "master_nails4.png",
                            Position = "Junior Nail Technician",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Martinez",
                            PhoneNumber = "+380009999999",
                            PhotoUrl = "master_makeup1.png",
                            Position = "Celebrity Makeup Artist",
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Isabella",
                            IsActive = true,
                            LastName = "Anderson",
                            PhoneNumber = "+380010101010",
                            PhotoUrl = "master_makeup2.png",
                            Position = "Bridal Makeup Specialist",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Mia",
                            IsActive = true,
                            LastName = "Thomas",
                            PhoneNumber = "+380011111111",
                            PhotoUrl = "master_makeup3.png",
                            Position = "Senior Makeup Artist",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Chloe",
                            IsActive = true,
                            LastName = "Jackson",
                            PhoneNumber = "+380012121212",
                            PhotoUrl = "master_makeup4.png",
                            Position = "Junior Makeup Artist",
                            Rating = 4.5
                        });
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.EmployeeSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("WorkEnd")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WorkStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeSchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfWeek = 1,
                            EmployeeId = 1,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayOfWeek = 2,
                            EmployeeId = 1,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayOfWeek = 3,
                            EmployeeId = 1,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DayOfWeek = 4,
                            EmployeeId = 1,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DayOfWeek = 5,
                            EmployeeId = 1,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DayOfWeek = 1,
                            EmployeeId = 2,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DayOfWeek = 2,
                            EmployeeId = 2,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DayOfWeek = 3,
                            EmployeeId = 2,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            DayOfWeek = 4,
                            EmployeeId = 2,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            DayOfWeek = 5,
                            EmployeeId = 2,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            DayOfWeek = 1,
                            EmployeeId = 3,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            DayOfWeek = 2,
                            EmployeeId = 3,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            DayOfWeek = 3,
                            EmployeeId = 3,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            DayOfWeek = 4,
                            EmployeeId = 3,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            DayOfWeek = 5,
                            EmployeeId = 3,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            DayOfWeek = 1,
                            EmployeeId = 4,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            DayOfWeek = 2,
                            EmployeeId = 4,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            DayOfWeek = 3,
                            EmployeeId = 4,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 19,
                            DayOfWeek = 4,
                            EmployeeId = 4,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            DayOfWeek = 5,
                            EmployeeId = 4,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 21,
                            DayOfWeek = 1,
                            EmployeeId = 5,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            DayOfWeek = 2,
                            EmployeeId = 5,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 23,
                            DayOfWeek = 3,
                            EmployeeId = 5,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            DayOfWeek = 4,
                            EmployeeId = 5,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 25,
                            DayOfWeek = 5,
                            EmployeeId = 5,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 26,
                            DayOfWeek = 1,
                            EmployeeId = 6,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 27,
                            DayOfWeek = 2,
                            EmployeeId = 6,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 28,
                            DayOfWeek = 3,
                            EmployeeId = 6,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 29,
                            DayOfWeek = 4,
                            EmployeeId = 6,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 30,
                            DayOfWeek = 5,
                            EmployeeId = 6,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 31,
                            DayOfWeek = 1,
                            EmployeeId = 7,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 32,
                            DayOfWeek = 2,
                            EmployeeId = 7,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 33,
                            DayOfWeek = 3,
                            EmployeeId = 7,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 34,
                            DayOfWeek = 4,
                            EmployeeId = 7,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 35,
                            DayOfWeek = 5,
                            EmployeeId = 7,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 36,
                            DayOfWeek = 1,
                            EmployeeId = 8,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 37,
                            DayOfWeek = 2,
                            EmployeeId = 8,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 38,
                            DayOfWeek = 3,
                            EmployeeId = 8,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 39,
                            DayOfWeek = 4,
                            EmployeeId = 8,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 40,
                            DayOfWeek = 5,
                            EmployeeId = 8,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 41,
                            DayOfWeek = 1,
                            EmployeeId = 9,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 42,
                            DayOfWeek = 2,
                            EmployeeId = 9,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 43,
                            DayOfWeek = 3,
                            EmployeeId = 9,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 44,
                            DayOfWeek = 4,
                            EmployeeId = 9,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 45,
                            DayOfWeek = 5,
                            EmployeeId = 9,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 46,
                            DayOfWeek = 1,
                            EmployeeId = 10,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 47,
                            DayOfWeek = 2,
                            EmployeeId = 10,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 48,
                            DayOfWeek = 3,
                            EmployeeId = 10,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 49,
                            DayOfWeek = 4,
                            EmployeeId = 10,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 50,
                            DayOfWeek = 5,
                            EmployeeId = 10,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 51,
                            DayOfWeek = 1,
                            EmployeeId = 11,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 52,
                            DayOfWeek = 2,
                            EmployeeId = 11,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 53,
                            DayOfWeek = 3,
                            EmployeeId = 11,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 54,
                            DayOfWeek = 4,
                            EmployeeId = 11,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 55,
                            DayOfWeek = 5,
                            EmployeeId = 11,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 56,
                            DayOfWeek = 1,
                            EmployeeId = 12,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 57,
                            DayOfWeek = 2,
                            EmployeeId = 12,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 58,
                            DayOfWeek = 3,
                            EmployeeId = 12,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 59,
                            DayOfWeek = 4,
                            EmployeeId = 12,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 60,
                            DayOfWeek = 5,
                            EmployeeId = 12,
                            WorkEnd = new TimeSpan(0, 18, 0, 0, 0),
                            WorkStart = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.EmployeeService", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("EmployeeServices");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            EmployeeId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            EmployeeId = 2,
                            ServiceId = 1
                        },
                        new
                        {
                            EmployeeId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            EmployeeId = 3,
                            ServiceId = 2
                        },
                        new
                        {
                            EmployeeId = 3,
                            ServiceId = 4
                        },
                        new
                        {
                            EmployeeId = 4,
                            ServiceId = 1
                        },
                        new
                        {
                            EmployeeId = 4,
                            ServiceId = 3
                        },
                        new
                        {
                            EmployeeId = 5,
                            ServiceId = 5
                        },
                        new
                        {
                            EmployeeId = 5,
                            ServiceId = 6
                        },
                        new
                        {
                            EmployeeId = 6,
                            ServiceId = 5
                        },
                        new
                        {
                            EmployeeId = 6,
                            ServiceId = 7
                        },
                        new
                        {
                            EmployeeId = 7,
                            ServiceId = 6
                        },
                        new
                        {
                            EmployeeId = 7,
                            ServiceId = 8
                        },
                        new
                        {
                            EmployeeId = 8,
                            ServiceId = 5
                        },
                        new
                        {
                            EmployeeId = 8,
                            ServiceId = 8
                        },
                        new
                        {
                            EmployeeId = 9,
                            ServiceId = 9
                        },
                        new
                        {
                            EmployeeId = 9,
                            ServiceId = 10
                        },
                        new
                        {
                            EmployeeId = 10,
                            ServiceId = 10
                        },
                        new
                        {
                            EmployeeId = 10,
                            ServiceId = 11
                        },
                        new
                        {
                            EmployeeId = 11,
                            ServiceId = 9
                        },
                        new
                        {
                            EmployeeId = 11,
                            ServiceId = 12
                        },
                        new
                        {
                            EmployeeId = 12,
                            ServiceId = 9
                        },
                        new
                        {
                            EmployeeId = 12,
                            ServiceId = 12
                        });
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DurationMinutes = 60,
                            Name = "Women's Haircut",
                            Price = 60m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            DurationMinutes = 90,
                            Name = "Hair Coloring",
                            Price = 85m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DurationMinutes = 45,
                            Name = "Wash & Blow Dry",
                            Price = 40m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DurationMinutes = 120,
                            Name = "Keratin Treatment",
                            Price = 150m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DurationMinutes = 45,
                            Name = "Classic Manicure",
                            Price = 25m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            DurationMinutes = 90,
                            Name = "Gel Manicure",
                            Price = 50m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            DurationMinutes = 90,
                            Name = "Nail Extensions",
                            Price = 85m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            DurationMinutes = 30,
                            Name = "Gel Removal",
                            Price = 15m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            DurationMinutes = 45,
                            Name = "Everyday Makeup",
                            Price = 50m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            DurationMinutes = 120,
                            Name = "Evening Makeup",
                            Price = 150m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            DurationMinutes = 120,
                            Name = "Bridal Makeup",
                            Price = 150m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            DurationMinutes = 90,
                            Name = "Makeup Trial",
                            Price = 100m
                        });
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Appointment", b =>
                {
                    b.HasOne("BeautySalon.DAL.Entities.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautySalon.DAL.Entities.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautySalon.DAL.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.EmployeeSchedule", b =>
                {
                    b.HasOne("BeautySalon.DAL.Entities.Employee", "Employee")
                        .WithMany("Schedules")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.EmployeeService", b =>
                {
                    b.HasOne("BeautySalon.DAL.Entities.Employee", "Employee")
                        .WithMany("EmployeeServices")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeautySalon.DAL.Entities.Service", "Service")
                        .WithMany("EmployeeServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Service", b =>
                {
                    b.HasOne("BeautySalon.DAL.Entities.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Employee", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("EmployeeServices");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("BeautySalon.DAL.Entities.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("EmployeeServices");
                });
#pragma warning restore 612, 618
        }
    }
}
